### PR TITLE
Introduce SobolGenerator

### PR DESCRIPTION
**Pull request by vishwakftw**
Once ready, will squash the commits and send to pytorch/pytorch.

Opened for reviewing purposes only.

cc: @Balandat

Pending tasks:

- [x] compile
- [ ] check for optimizations
- [ ] test cases

### CODE REVIEW

**Comment by vishwakftw** [comment]
I will compile this tomorrow, and fix bugs if any. After that I think adding the Python bindings should be pretty straight forward.

**Comment by vishwakftw** [comment]
I haven't added a provision for a random seed, which I might need help from core devs. Once this is sent upstream, I will work on a patch there.

**Comment by Balandat** [comment]
This looks great so far, thanks a lot for the work. The python unit tests I provided in https://github.com/pytorch/pytorch/issues/9332#issuecomment-404882333 should provide decent coverage, so porting these over it should be straightforward to test this.

**Comment by Balandat** [comment]
I think being able to set the seed for the scrambling would be an important thing to have. Are you still planning to add this with the help of some core pytorch folks?

**Comment by vishwakftw** [comment]
If approach 1 is taken in the two approaches I specified in the issue upstream, then setting the random seed should not be an issue at all. I am waiting for Soumith’s reply, after which any modifications required can be done and then sent upstream.

**Comment by vishwakftw** [comment]
Closing this based on discussion. Will open a new one with the suggested implementation shortly.

**Pull request closed without merging**
